---
- name: Setup LEMP Stack on Ubuntu 20.04
  hosts: local
  become: yes

  vars:
    php_packages:
      - php-fpm
      - php-mysql
      - php-cli
      - php-curl
      - php-xml
      - php-mbstring
    web_root: /var/www/html

  tasks:
  - name: Update apt packages
    apt:
      update_cache: yes
      cache_valid_time: 3600

  - name: Install Nginx
    apt:
      name: nginx
      state: present

  - name: Ensure Nginx running
    service:
      name: nginx
      state: started
      enabled: yes

  - name: Install MySQL server
    apt:
      name: mysql-server
      state: present

  - name: Ensure MySQL running
    service:
      name: mysql
      state: started
      enabled: yes

  - name: Install PHP and modules
    apt:
      name: "{{ php_packages }}"
      state: present

  - name: Configure Nginx for PHP
    copy:
      dest: /etc/nginx/sites-available/default
      content: |
        server {
          listen 80 default_server;
          listen [::]:80 default_server;
          root /var/www/html;
          index index.php index.html index.htm;
          server_name _;

          location / {
            try_files $uri $uri/ =404;
          }

          location ~\.php$ {
            include snippets/fastcgi-php.conf;
            fastcgi_pass unix:/run/php/php8.3-fpm.sock;
          }

          location ~/\.ht {
            deny all;
          }
        }
    notify:
      - Restart nginx

  - name: Create PHP test file
    copy:
      dest: "{{ web_root }}/info.php"
      content: |
        <?php
        phpinfo();
        ?>

  - name: Set permissions
    file:
      path: "{{ web_root }}"
      owner: www-data
      group: www-data
      mode: '0755'
      recurse: yes

  handlers:
    - name: Restart nginx
      service:
        name: nginx
        state: restarted
